version: "3.9"
services: 
    webserver:
      image: nginx:alpine
      container_name: assessment-backend-xp-nginx
      ports:
        - "8000:80"
      networks:
        - web-dev
      volumes:
        - ${PWD}/phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        - ${PWD}/:/var/www/assessment-backend-xp
        - ${PWD}/phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini
    php8:
      build: phpdocker/php-fpm
      image: php8.1.6-fpm
      container_name: assessment-backend-xp-php
      volumes: 
        - ${PWD}/:/var/www/assessment-backend-xp
      ports: 
        - "9000:9000"
      networks: 
        - web-dev

    mariadb:
      image: 'mariadb:10.6'
      container_name: assessment-backend-xp-mariadb
      volumes: 
        - ${PWD}/phpdocker/mariadb:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: toor
        MYSQL_DATABASE: webjump-test
        MYSQL_USER: root
        MYSQL_PASSWORD: toor
      restart: on-failure
      ports:
        - "3307:3306"
      networks: 
        - web-dev
networks: 
      web-dev:
        driver: bridge